framework:
  messenger:
    failure_transport: failed

    transports:
      async:
        dsn: 'doctrine://default'
        options:
          use_notify: true
          check_delayed_interval: 60000
        retry_strategy:
          max_retries: 3
          multiplier: 2
      failed:
        dsn: 'doctrine://default?queue_name=failed'

    routing: